version: 2
jobs:
  build:
    working_directory: ~/tale

    docker: 
      - image: circleci/openjdk:9-jdk-browsers 

    steps: 

      - checkout

      - restore_cache: 
          key: tale-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: tale-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - run:
          name: build deb package
          command: echo $CIRCLE_BUILD_NUM # ls -alh ./target/dist

#     - run:
#         name: build deb package
#         command: ~/tale/.ci/build_deb.sh $CIRCLE_BUILD_NUM

#     - run:
#         name: ls
#         command: ls -al ~/tale/target/dist
