version: 2
jobs:
  build:
#   working_directory: ~/circleci-demo-java-spring 

    docker: 
      - image: circleci/openjdk:8-jdk-browsers 

    steps: 

      - checkout
      - run:
          name: HI!
          command: echo "Hello, World!"
      - run:
          name: Print current time
          command: date
