version: 2
jobs:
  build:
    working_directory: ~/tale

    docker: 
      - image: circleci/openjdk:9-jdk-browsers 

    steps: 

      - checkout

      - restore_cache: 
          key: tale-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: tale-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - run:
          name: tar 
          command: tar -C ~/tale/target/dist/ -zxvf ~/tale/target/dist/tale.tar.gz

      - run:
          name: find
          command: find ./ -name "*.jar"

#     - run:
#         name: build deb package
#         command: ~/tale/.ci/build_deb.sh

#     - run:
#         name: ls
#         command: ls -al ~/tale/target/dist
